export const DEFAULT_ACTION = 'DEFAULT_ACTION';

export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_ERROR = 'FETCH_STUDENTS_ERROR';

//#region Reset doable for this state
export const RESET_STUDENT_DOABLES = 'RESET_STUDENT_DOABLES';
export const TOGGLE_STUDENT_BOOLEANABLE_STATE = 'TOGGLE_STUDENT_BOOLEANABLE_STATE';
export const TOGGLE_STUDENT_ERRABLE_STATE = 'TOGGLE_STUDENT_ERRABLE_STATE';
export const TOGGLE_STUDENT_SUCCESSIBLE_STATE = 'TOGGLE_STUDENT_SUCCESSIBLE_STATE';
//#endregion

/* new-constant-export-goes-here */